[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
chrono-tz = "0.10"
reqwest = { version = "0.12", features = ["blocking"] }
regex = "1.1"
itertools = "0.13"